apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-image
      image: norhanyounis/webimage 
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80