apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: Mohammed

  ports:
    - port: 8080 # Cluster Ip service port
      targetPort: 8080 #pod/container port
      nodePort: 32000 #Any port between 30000 and 32767 [OPTIONAL]